#!/bin/sh

if [ -z $1 ]; then
	echo Usage: $0 release_version
	exit 1
fi

VERSION=$1
REPO_BASE_PUBLIC=http://cdn.hashland.cc/hlos
REPO_BASE_DIR=/var/www/cdn.hashland.cc/hlos

for config in $(ls target_config); do
	cp target_config/$config .config
	echo CONFIG_VERSION_NUMBER=\"$VERSION\">>.config
	echo CONFIG_VERSION_REPO=\"$REPO_BASE_PUBLIC/$VERSION\">>.config

	rm -rf bin
	make defconfig
	make -j4

	# uncompress all compressed images because we only want to publish uncompressed images
	find bin/targets -name "*sdcard*gz" -exec gzip -d {} +

	RSYNC_ARGS=""
	if ssh root@cdn.hashland.cc mkdir $REPO_BASE_DIR/$VERSION/; then
		RSYNC_ARGS=""
		UPDATE=0
	else
		# do not update target once it was created
		RSYNC_ARGS="--exclude targets/"
		UPDATE=1
	fi

	rsync -avz $RSYNC_ARGS bin/ root@cdn.hashland.cc:$REPO_BASE_DIR/$VERSION/
done

if [ "$UPDATE" = 0 ]; then
	hl create_sysimage "name=baikal,giant-b&version=$VERSION&url=$REPO_BASE_PUBLIC/$VERSION/targets/sunxi/cortexa7/hashland-$VERSION-sunxi-cortexa7-baikal-giant-b-squashfs-sdcard.img"
fi

